# Generated by Django 4.1.7 on 2023-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sampleapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("age", models.IntegerField(default=0)),
                ("place", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("mobileNumber", models.PositiveIntegerField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
